<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Categorie2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie2Repository extends EntityRepository
{
}
