<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Categorie4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie4Repository extends EntityRepository
{
}
