<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Categorie3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie3Repository extends EntityRepository
{
}
